exports.REQUEST_RANDOM_FILE = 'magicBeans.requestRandomFile'
exports.REQUEST_RANDOM_FILE = 'magicBeans.requestRandomFile'
exports.SORT_LINES = 'magicBeans.sortLines'
exports.SLOW_SCROLL_INIT = 'magicBeans.slowScrollInit'
exports.SLOW_SCROLL_START = 'magicBeans.slowScrollStart'
