exports.REQUEST_RANDOM_FILE = 'magicBeans.requestRandomFile'
exports.REQUEST_RANDOM_FILE_WITH_SUBFOLDER = 'magicBeans.requestRandomFileWithSubfolder'
exports.SORT_LINES = 'magicBeans.sortLines'
exports.SLOW_SCROLL_INIT = 'magicBeans.slowScrollInit'
exports.SLOW_SCROLL_START = 'magicBeans.slowScrollStart'
exports.SYMBOLS_LIST = 'magicBeans.symbolsList'
