exports.REQUEST_RANDOM_FILE = 'magicBeans.requestRandomFile'
exports.SORT_LINES = 'magicBeans.sortLines'
exports.SLOW_SCROLL_INIT = 'magicBeans.slowScrollInit'
exports.SLOW_SCROLL_START = 'magicBeans.slowScrollStart'
exports.SLOW_SCROLL_STOP = 'magicBeans.slowScrollStop'
// used with configAnt, so no need for prefix
exports.THEME_CHANGE_DAYTIME = 'THEME_CHANGE_DAYTIME'
exports.SLOW_SCROLL_SHOW_BAR_INITIALLY = 'SLOW_SCROLL_SHOW_BAR_INITIALLY'
exports.SLOW_SCROLL_KEY = 'SLOW_SCROLL_KEY'
exports.IS_VSCODE_INSIDERS = 'IS_VSCODE_INSIDERS'
exports.IS_CURSOR = 'IS_CURSOR'
